enum TetrisAction {
  NEW_GAME = "NEW_GAME",
  TOGGLE_PAUSE_RESUME = "TOGGLE_PAUSE_RESUME",
  MOVE_PIECE = "MOVE_PIECE",
  HARD_DROP = "HARD_DROP",
  ROTATE_PIECE = "ROTATE_PIECE",
  MOVE_PIECE_DOWN = "MOVE_PIECE_DOWN",
  HANDLE_PIECE_MOVEMENT = "HANDLE_PIECE_MOVEMENT",
  MERGE_PIECE_TO_GRID = "MERGE_PIECE_TO_GRID",
  SPAWN_NEXT_PIECE = "SPAWN_NEXT_PIECE",
}

export { TetrisAction };
